# Generated by Django 5.2.1 on 2025-05-08 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_restaurant_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='is_pulished',
            new_name='is_published',
        ),
    ]
