# Generated by Django 5.2.1 on 2025-05-10 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_is_pulished_menu_is_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price_at_order',
            new_name='price',
        ),
    ]
