# Generated by Django 5.2.1 on 2025-05-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_userprofile_userdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
