# Generated by Django 5.2.1 on 2025-05-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userdetail_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.TextField(blank=True, default='A variety of dishes for every taste.'),
        ),
    ]
